name: Draw Keymap

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - .github/workflows/draw.yml
      - keymap_drawer.config.yaml

jobs:
  draw:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3.0
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message }}"
      destination: "commit"
      fail_on_error: true
